[default]
extend-ignore-re = [
  # Technical terms and identifiers
  "([A-Z][a-z]*){2,}", # CamelCase
  "[a-z]+_[a-z]+",     # snake_case variables
]

[default.extend-words]
# Add your project-specific terms here
# Rust ecosystem crates
serde = "serde"
rustfmt = "rustfmt"
clippy = "clippy"
tokio = "tokio"

# Money/Currency terms
BTC = "BTC"
ETH = "ETH"
USD = "USD"
EUR = "EUR"
GBP = "GBP"
JPY = "JPY"
CAD = "CAD"
CHF = "CHF"
AUD = "AUD"
NZD = "NZD"
CNY = "CNY"
KRW = "KRW"
SGD = "SGD"
HKD = "HKD"
TWD = "TWD"
INR = "INR"
SEK = "SEK"
NOK = "NOK"
DKK = "DKK"
PLN = "PLN"
CZK = "CZK"
HUF = "HUF"
BRL = "BRL"
MXN = "MXN"
ARS = "ARS"
CLP = "CLP"
ZAR = "ZAR"
EGP = "EGP"
AED = "AED"
SAR = "SAR"
ILS = "ILS"
TRY = "TRY"
# Regional Currencies
RON = "RON"
BGN = "BGN"
HRK = "HRK"
RSD = "RSD"
UAH = "UAH"
THB = "THB"
MYR = "MYR"
IDR = "IDR"
PHP = "PHP"
VND = "VND"
COP = "COP"
PEN = "PEN"
UYU = "UYU"
BOB = "BOB"
PYG = "PYG"
NGN = "NGN"
KES = "KES"
GHS = "GHS"
MAD = "MAD"
TND = "TND"
QAR = "QAR"
KWD = "KWD"
BHD = "BHD"
OMR = "OMR"
JOD = "JOD"

# Currency subdivisions
fils = "fils"         # UAE Dirham subdivision
halalas = "halalas"   # Saudi Riyal subdivision
agorot = "agorot"     # Israeli Shekel subdivision
kurus = "kuruş"       # Turkish Lira subdivision
groszy = "groszy"     # Polish Złoty subdivision
haleru = "haléřů"     # Czech Koruna subdivision
piastres = "piastres" # Egyptian Pound subdivision
centavos = "centavos" # Various Latin American currencies
# Regional currency subdivisions
bani = "bani"         # Romanian Leu subdivision
stotinki = "stotinki" # Bulgarian Lev subdivision
lipa = "lipa"         # Croatian Kuna subdivision
para = "para"         # Serbian Dinar subdivision
kopiyok = "kopiyok"   # Ukrainian Hryvnia subdivision
satang = "satang"     # Thai Baht subdivision
sen = "sen"           # Malaysian Ringgit subdivision
centesimos = "centésimos" # Uruguayan Peso subdivision
baisa = "baisa"       # Omani Rial subdivision
millimes = "millimes" # Tunisian Dinar subdivision

# Technical terms
bigdecimal = "bigdecimal"
auditability = "auditability"

[files]
extend-exclude = ["target/", "Cargo.lock", "*.log", ".git/"]
